const ER_NO_SUCH_TABLE = "ER_NO_SUCH_TABLE";
const ER_BAD_FIELD_ERROR = "ER_BAD_FIELD_ERROR";
const ER_TOO_LONG_IDENT = "ER_TOO_LONG_IDENT";
const ER_DUP_KEYNAME = "ER_DUP_KEYNAME";
const ER_WRONG_FIELD_SPEC = "ER_WRONG_FIELD_SPEC";
const ER_EMPTY_QUERY = "ER_EMPTY_QUERY";
const ER_PARSE_ERROR = "ER_PARSE_ERROR";
const ER_TOO_LONG_KEY = "ER_TOO_LONG_KEY";
const ER_KEY_COLUMN_DOES_NOT_EXITS = "ER_KEY_COLUMN_DOES_NOT_EXITS";

module.exports = {
    ER_NO_SUCH_TABLE,
    ER_BAD_FIELD_ERROR,
    ER_TOO_LONG_IDENT,
    ER_DUP_KEYNAME,
    ER_WRONG_FIELD_SPEC,
    ER_EMPTY_QUERY,
    ER_PARSE_ERROR,
    ER_TOO_LONG_KEY,
    ER_KEY_COLUMN_DOES_NOT_EXITS
}